name: Release new Version ğŸš€

on:
  push:
    tags:
      - v*

permissions:
  contents: write 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: ğŸ·ï¸ EExtract tag name
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: ğŸ”€ Switch to main and merge new release
        run: |
          git checkout main
          git merge --no-ff "$TAG" -m "release: $TAG"

      - name: ğŸ¦€ Bump version in Cargo.toml
        run: sed -i -E "s/^version\s*=\s*\"[0-9]+\.[0-9]+\.[0-9]+\"/version = \"${TAG#v}\"/" Cargo.toml
      
      - name: â„ï¸ Bump version in flake.nix
        run: sed -i -E "s/^(\s*)version\s*=\s*\"[0-9]+\.[0-9]+\.[0-9]+\";/\1version = \"${TAG#v}\";/" flake.nix

      - name: ğŸ“ Commit (amend) bumped versions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml flake.nix
          git commit --amend --no-edit

      - name: ğŸš€ Push new release
        run: git push origin main
